INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(1,'Caito','Vilas','caitocd@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(2,'Rosana','Medrano','rosana@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(3,'Tamara','Vilas','tamara@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(4,'Martin','Vilas','martin@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(5,'Adrian','Maldonado','adrian@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(6,'Antonio','Tano','tano@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(7,'Brian','Fernandez','brian@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(8,'Camila','Segovia','camila@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(9,'Carlos','Peruano','peru@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(10,'Cecilia','Psicologa','cecilia@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(11,'Sandra','Villegas','chichu@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(12,'Daniel','Acevedo','daniel@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(13,'Daniel','Lemos','dlemos@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(14,'Debora','Vilas','debora@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(15,'Diego','Vilas','diego@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(16,'Emiliano','Culotta','emiliano@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(17,'Emilio','Luis','emilio@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(18,'Enrique','Epecuen','enrique@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(19,'Fabiana','Medrano','fabiana@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(20,'Gisela','Barsena','gisela@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(21,'Gladis','Cordoba','gladis@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(22,'Hernan','Seguro','hernan@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(23,'Joaquin','Vilas','joaco@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(24,'Juan','Vilas','juan@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(25,'JUan Pablo','Vilas','jp@gmail.com','2020-11-26','');
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto) VALUES(26,'Karina','Piki','karina@gmail.com','2020-11-26','');

/* Populate tabla productos */
INSERT INTO productos(nombre, precio, create_at) VALUES('Panasonic Pantalla LCD',15500.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Sony Camara Digital DSC-W320B',41000.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Apple Ipod shuffle',14900.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Sony Notebook Z110',120500.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('HP Multifuncion F2280',43000.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Bianchi Bicicleta 26',69000.00, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Mica Comoda 5 cajones',29800.00, NOW());